name: Static Analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          node-version: ${{ matrix.node-version }}
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
