name: Static Analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-analysis:
    name: "Echidna and Slither"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        testName:
          - VaultMathEchidnaTest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - name: Compile
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
          REPORT_GAS: false
          FORKING: true
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: yarn compile
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Install pip
      - name: Install pip3
        run: |
          python -m pip install --upgrade pip

      # Install Slither
      - name: Install slither
        run: |
          pip3 install slither-analyzer

      # Install Echidna
      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.7.2/echidna-test-1.7.2-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test

      # Run Echidna logical tests
      - name: Run ${{ matrix.testName }}
        if: always()
        run: echidna-test . --contract ${{ matrix.testName }} --config echidna.config.yml

      # Run Slither static analysis
      - name: Run Slither static analysis
        if: always()
        run: slither --npx-disable --hardhat-ignore-compile --exclude-dependencies --exclude-informational --exclude-low  --exclude controlled-delegatecall,divide-before-multiply,unused-return,arbitrary-send .
