name: Coverage

on:
  push:
    branches: [master]
  pull_request:

jobs:
  integration-tests:
    name: "Run Coverage Report"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install

      # Run coverage
      - name: Run coverage analysis
        run: yarn coverage
