name: Coverage

on:
  push:
    branches: [master]

jobs:
  integration-tests:
    name: "Run Coverage Report"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Run yarn install
        run: yarn install

      - name: Run yarn compile
        run: yarn compile

      - name: Run coverage analysis
        run: yarn coverage
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          FORK_URL: ${{ secrets.FORK_URL }}
          REPORT_GAS: false
          FORKING: true
