name: Coverage

on:
  workflow_dispatch:

jobs:
  integration-tests:
    name: "Run Coverage Report"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Setup yarn
      - name: Install yarn
        run: npm install -g yarn

      # Cache dependencies for faster build time in future
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./.yarn
          key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}

      # Install GYP as build dependencies
      - name: Install GYP
        run: |
          npm install node-gyp -g
          npm install node-gyp-build -g

      # Install project dependencies
      - name: Install dependencies
        run: |
          yarn install --prefer-offline  --cache-folder .yarn --modules-folder node_modules

      # Run coverage
      - name: Run coverage analysis
        run: yarn coverage
