name: Deploy to Testnet

on:
  workflow_dispatch:

jobs:
  deployment:
    name: "Build & Migrate to Testnet"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    # Only deploy from master
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Run yarn install
        run: yarn install

      - name: Run yarn compile
        run: yarn compile
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Configure git information
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com

      - name: Deploy
        env:
          TESTNET_ALCHEMY_API_KEY: ${{ secrets.TESTNET_ALCHEMY_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          REPORT_GAS: false
          FORKING: false
        run: |
          yarn deploy --network goerli
          yarn export-abi

      - name: Prepare release files
        run: |
          git add .
          git commit -am "feat: new testnet deployment"
          git push

      - name: Pushes the smart contract addresses to the deployed repo
        id: push_addresses
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          source-directory: deployments/
          destination-github-username: "Ithil-protocol"
          destination-repository-name: "deployed"
          user-email: info@ithil.fi
          commit-message: "new addresses"
          target-branch: master
          target-directory: latest

      - name: Pushes the smart contract abi to the deployed repo
        id: push_abi
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          source-directory: abi/
          destination-github-username: "Ithil-protocol"
          destination-repository-name: "deployed"
          user-email: info@ithil.fi
          commit-message: "new abi"
          target-branch: master
          target-directory: abi
