name: Deploy to Testnet

on:
  workflow_dispatch:

jobs:
  deployment:
    name: "Build & Migrate to Testnet"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    # Only deploy from master
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - name: Run yarn compile
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: yarn compile

      # Configure Git information
      - name: Configure git information
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com

      # Deploy smart contracts to Rinkeby testnet
      - name: Deploy
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          REPORT_GAS: false
          FORKING: false
        run: |
          yarn deploy --network rinkeby
          yarn export-abi

      # Prepare release files from arifacts
      - name: Prepare release files
        run: |
          git add .
          git commit -am "feat: new testnet deployment"
          git push
