name: Linting

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eslint:
    name: "Run Solhint"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn solhint -c .solhint.json contracts/**/*.sol
