name: Integration Testing

on:
  push:
    branches: [master]
  pull_request:

jobs:
  integration-tests:
    name: "Run Integration Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Run yarn install
        run: yarn install

      - name: Run yarn compile
        run: yarn compile

      - name: Run integration tests
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          REPORT_GAS: false
          FORKING: true
        run: yarn test
